GOPATH=/Users/tokusei/.go ~/.go/bin/gox -osarch="darwin/amd64" ./...
# GOPATH=/Users/tokusei/.go ~/.go/bin/gox -osarch="windows/amd64" ./...

cp robip-tool-go_darwin_amd64 "./Robip Tool.app/Contents/MacOS/robip-tool-go"
